In [106]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [107]:
RAW_DATA_PATH = "../data/raw/"

In [108]:
submission_df = pd.read_json(RAW_DATA_PATH + "submissions.json")

In [109]:
submission_df.head()

,_id,userId,problemId,contestId,language,fileContent,time,memory,output,status,points,createdAt,updatedAt,__v,duringContest
0,{'$oid': '5b649806c0b1b80020eb30e0'},{'$oid': '5b6490e95969e7002076f330'},{'$oid': '5b5c8cd7276e2200208fed62'},{'$oid': '5b5c89ef30db8a0020962414'},C,https://firebasestorage.googleapis.com/v0/b/si...,0s,0KB,https://firebasestorage.googleapis.com/v0/b/si...,Time Limit Exceeded,0,{'$date': {'$numberLong': '1533299374750'}},{'$date': {'$numberLong': '1541917278621'}},0,True
1,{'$oid': '5b65596264290b0020a95953'},{'$oid': '5b65571764290b0020a95951'},{'$oid': '5b645f711b2cd40020b6c771'},{'$oid': '5b5ca6d47cf0b100209fe49a'},Python3,https://firebasestorage.googleapis.com/v0/b/si...,0.04s,27704KB,https://firebasestorage.googleapis.com/v0/b/si...,Accepted,100,{'$date': {'$numberLong': '1533368674774'}},{'$date': {'$numberLong': '1605269658479'}},0,True
2,{'$oid': '5b6571fe64290b0020a95958'},{'$oid': '5b655dd264290b0020a95955'},{'$oid': '5b645f711b2cd40020b6c771'},{'$oid': '5b5ca6d47cf0b100209fe49a'},Java,https://firebasestorage.googleapis.com/v0/b/si...,0s,0KB,https://firebasestorage.googleapis.com/v0/b/si...,Runtime Error,-10,{'$date': {'$numberLong': '1533374974361'}},{'$date': {'$numberLong': '1605269658481'}},0,True
3,{'$oid': '5b65a3f764290b0020a95964'},{'$oid': '5b5d756b37392f89933e7515'},{'$oid': '5b649819c0b1b80020eb30e1'},{'$oid': '5b5ca6d47cf0b100209fe49a'},Java,https://firebasestorage.googleapis.com/v0/b/si...,0s,0KB,https://firebasestorage.googleapis.com/v0/b/si...,Runtime Error,-10,{'$date': {'$numberLong': '1533387767583'}},{'$date': {'$numberLong': '1605269658482'}},0,True
4,{'$oid': '5b65c1133d20f50020733314'},{'$oid': '5b647abb58d190002048aaba'},{'$oid': '5b649819c0b1b80020eb30e1'},{'$oid': '5b5ca6d47cf0b100209fe49a'},Python,https://firebasestorage.googleapis.com/v0/b/si...,0.02s,23336KB,https://firebasestorage.googleapis.com/v0/b/si...,Wrong Answer,-10,{'$date': {'$numberLong': '1533395219101'}},{'$date': {'$numberLong': '1605269658483'}},0,True

In [110]:
TO_REMOVE = ["__v","_id","contestId","createdAt","duringContest","fileContent","memory","output","points","time","updatedAt","userId"]

In [111]:
df = submission_df.drop(TO_REMOVE, axis=1)

In [112]:
df.head()

                              problemId language               status
0  {'$oid': '5b5c8cd7276e2200208fed62'}        C  Time Limit Exceeded
1  {'$oid': '5b645f711b2cd40020b6c771'}  Python3             Accepted
2  {'$oid': '5b645f711b2cd40020b6c771'}     Java        Runtime Error
3  {'$oid': '5b649819c0b1b80020eb30e1'}     Java        Runtime Error
4  {'$oid': '5b649819c0b1b80020eb30e1'}   Python         Wrong Answer

In [113]:
df["problemId"] = df["problemId"].apply(lambda x: x["$oid"])

In [114]:
df.head()

                  problemId language               status
0  5b5c8cd7276e2200208fed62        C  Time Limit Exceeded
1  5b645f711b2cd40020b6c771  Python3             Accepted
2  5b645f711b2cd40020b6c771     Java        Runtime Error
3  5b649819c0b1b80020eb30e1     Java        Runtime Error
4  5b649819c0b1b80020eb30e1   Python         Wrong Answer

In [115]:
TO_REPLACE = ["Wrong Answer","Runtime Error","Time Limit Exceeded","Compilation Error"]
REPLACE_WITH = "Not Accepted"

df.replace(TO_REPLACE,REPLACE_WITH,inplace=True)

In [116]:
df.head()

                  problemId language        status
0  5b5c8cd7276e2200208fed62        C  Not Accepted
1  5b645f711b2cd40020b6c771  Python3      Accepted
2  5b645f711b2cd40020b6c771     Java  Not Accepted
3  5b649819c0b1b80020eb30e1     Java  Not Accepted
4  5b649819c0b1b80020eb30e1   Python  Not Accepted

In [117]:
TO_REPLACE_LANGUAGE = ["C++14"]
REPLACE_WITH_LANGUAGE = "C++"

df.replace(TO_REPLACE_LANGUAGE,REPLACE_WITH_LANGUAGE,inplace=True)

In [118]:
df.head()

                  problemId language        status
0  5b5c8cd7276e2200208fed62        C  Not Accepted
1  5b645f711b2cd40020b6c771  Python3      Accepted
2  5b645f711b2cd40020b6c771     Java  Not Accepted
3  5b649819c0b1b80020eb30e1     Java  Not Accepted
4  5b649819c0b1b80020eb30e1   Python  Not Accepted

In [119]:
df.language.value_counts()

Python3       4194
C++           2599
C             1468
Java          1082
Python          45
Go              17
Javascript      11
Name: language, dtype: int64

In [120]:
UNIQUE_PROBLEMS = df.problemId.unique()

In [121]:
group_language = df.groupby(["language","status","problemId"]).size().reset_index(name="count")
group_language.head()

  language    status                 problemId  count
0        C  Accepted  5b5c8cd7276e2200208fed62     16
1        C  Accepted  5b645f711b2cd40020b6c771      5
2        C  Accepted  5b64600d1b2cd40020b6c772      3
3        C  Accepted  5b649819c0b1b80020eb30e1      5
4        C  Accepted  5b6c3ec18cab100020e963b7     14

In [122]:
group_prob_status = df.groupby(["problemId","status"]).count()
group_prob_status.reset_index(inplace=True)

In [123]:
group_prob_status.head()

                  problemId        status  language
0  5b5c8cd7276e2200208fed62      Accepted        79
1  5b5c8cd7276e2200208fed62  Not Accepted       133
2  5b645f711b2cd40020b6c771      Accepted        41
3  5b645f711b2cd40020b6c771  Not Accepted        45
4  5b64600d1b2cd40020b6c772      Accepted        33

In [124]:
TO_REPLACE_STATUS = ["Accepted","Not Accepted"]
REPLACE_WITH_STATUS = [1,0]

group_prob_status.replace(TO_REPLACE_STATUS,REPLACE_WITH_STATUS,inplace=True)

In [125]:
group_prob_status.head()

                  problemId  status  language
0  5b5c8cd7276e2200208fed62       1        79
1  5b5c8cd7276e2200208fed62       0       133
2  5b645f711b2cd40020b6c771       1        41
3  5b645f711b2cd40020b6c771       0        45
4  5b64600d1b2cd40020b6c772       1        33

In [126]:
problem_group_language = dict()

for problem in UNIQUE_PROBLEMS:
    problem_group_language[problem] = {
        1 : group_prob_status[group_prob_status.problemId == problem].language.values[0] if (group_prob_status[group_prob_status.problemId == problem].status == 1).any() else 0,
        0 : group_prob_status[group_prob_status.problemId == problem].language.values[1] if len(group_prob_status[group_prob_status.problemId == problem].language.values) > 1 else group_prob_status[group_prob_status.problemId == problem].language.values[0] if (group_prob_status[group_prob_status.problemId == problem].status == 0).any() else 0
    }

In [127]:

problem_group_language["6301b5768296fc0022ebb48a"]

{1: 0, 0: 14}

In [128]:
group_language.replace(TO_REPLACE_STATUS,REPLACE_WITH_STATUS,inplace=True)

In [129]:
problem_group_particular_language = dict()

for problem in UNIQUE_PROBLEMS:
    problem_group_particular_language[problem] = {
        'Python3':{
        1 : group_language[(group_language.problemId == problem) & (group_language.language == "Python3") & group_language.status == 1]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Python3")]['status'] == 1).any() else 0,
        0 : group_language[(group_language.problemId == problem) & (group_language.language == "Python3") & (group_language.status == 0)]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Python3")]['status'] == 0).any() else 0,
        },
        'C++':{
        1 : group_language[(group_language.problemId == problem) & (group_language.language == "C++") & group_language.status == 1]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "C++")]['status'] == 1).any() else 0,
        0 : group_language[(group_language.problemId == problem) & (group_language.language == "C++") & (group_language.status == 0)]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "C++")]['status'] == 0).any() else 0,
        },
        'Java':{
        1 : group_language[(group_language.problemId == problem) & (group_language.language == "Java") & group_language.status == 1]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Java")]['status'] == 1).any() else 0,
        0 : group_language[(group_language.problemId == problem) & (group_language.language == "Java") & (group_language.status == 0)]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Java")]['status'] == 0).any() else 0,
        },
        'C':{
        1 : group_language[(group_language.problemId == problem) & (group_language.language == "C") & group_language.status == 1]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "C")]['status'] == 1).any() else 0,
        0 : group_language[(group_language.problemId == problem) & (group_language.language == "C") & (group_language.status == 0)]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "C")]['status'] == 0).any() else 0,
        },
        'Python':{
        1 : group_language[(group_language.problemId == problem) & (group_language.language == "Python") & group_language.status == 1]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Python")]['status'] == 1).any() else 0,
        0 : group_language[(group_language.problemId == problem) & (group_language.language == "Python") & (group_language.status == 0)]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Python")]['status'] == 0).any() else 0,
        }, 
        'Go':{
        1 : group_language[(group_language.problemId == problem) & (group_language.language == "Go") & group_language.status == 1]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Go")]['status'] == 1).any() else 0,
        0 : group_language[(group_language.problemId == problem) & (group_language.language == "Go") & (group_language.status == 0)]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Go")]['status'] == 0).any() else 0,
        }, 
        'Javascript':{
        1 : group_language[(group_language.problemId == problem) & (group_language.language == "Javascript") & group_language.status == 1]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Javascript")]['status'] == 1).any() else 0,
        0 : group_language[(group_language.problemId == problem) & (group_language.language == "Javascript") & (group_language.status == 0)]['count'].values[0] if (group_language[(group_language.problemId == problem) & (group_language.language == "Javascript")]['status'] == 0).any() else 0,
        }, 
    }

In [130]:
group_language[group_language.problemId == "5b5c8cd7276e2200208fed62"]

    language  status                 problemId  count
0          C       1  5b5c8cd7276e2200208fed62     16
75         C       0  5b5c8cd7276e2200208fed62     49
186      C++       1  5b5c8cd7276e2200208fed62     28
365      C++       0  5b5c8cd7276e2200208fed62     38
551       Go       0  5b5c8cd7276e2200208fed62      5
555     Java       1  5b5c8cd7276e2200208fed62     10
665     Java       0  5b5c8cd7276e2200208fed62     17
792   Python       0  5b5c8cd7276e2200208fed62      1
815  Python3       1  5b5c8cd7276e2200208fed62     25
993  Python3       0  5b5c8cd7276e2200208fed62     23

In [131]:
from operator import itemgetter
for key,value in problem_group_language.items():
    if value[0] + value[1] == 0:
        problem_group_language[key] = 0
    else:
        problem_group_language[key] = (value[1] / (value[0] + value[1]))

In [132]:
for key,value in problem_group_particular_language.items():
    for key1,value1 in value.items():
        if(value1[0] + value1[1] != 0):
            problem_group_particular_language[key][key1] = value1[1]/(value1[0] + value1[1])
        else:
            problem_group_particular_language[key][key1] = 0

In [133]:
success_score = dict()
for problems in UNIQUE_PROBLEMS:
    temp = []
    languages = []
    for language in group_language.language.unique():
        languages.append(language)
        temp.append(1 / (1 + (problem_group_language[problems] - problem_group_particular_language[problems][language])))
        
    success_score[problems] = dict(zip(languages,temp))

In [134]:
x = pd.DataFrame.from_dict(success_score, orient='index')
x.columns.name = 'problemId'
x

problemId,C,C++,Go,Java,Javascript,Python,Python3
5b5c8cd7276e2200208fed62,0.887715,1.054408,0.728522,0.997734,0.728522,0.728522,1.173973
5b645f711b2cd40020b6c771,0.834052,1.267035,0.677165,0.839609,0.677165,2.097561,1.053778
5b649819c0b1b80020eb30e1,1.282717,0.994248,0.835938,0.857663,0.835938,0.835938,1.085468
5b64600d1b2cd40020b6c772,1.030303,1.030303,0.507463,0.854271,0.507463,0.507463,1.030303
5b6c3ec18cab100020e963b7,0.882090,1.128932,0.735577,1.032873,0.735577,0.735577,1.288421
...,...,...,...,...,...,...,...
63a2b5b7a198a20018e909d9,0.639344,0.867801,0.639344,0.991525,0.639344,0.639344,1.258065
63a2b688a198a20018e909db,0.888889,1.034014,0.888889,1.000000,0.888889,0.888889,0.986301
63a2b83da198a20018e909df,0.850000,1.079365,0.850000,0.990291,0.850000,0.850000,0.914798
63a2b900a198a20018e909e1,0.666667,2.000000,0.666667,0.857143,0.666667,0.666667,1.200000
63a2b9c9a198a20018e909e3,0.880000,7.333333,0.880000,1.128205,0.880000,0.880000,0.880000

In [135]:
x.describe()

problemId,C,C++,Go,Java,Javascript,Python,Python3
count,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000
mean,0.886071,1.233051,0.864222,1.060832,0.780618,0.802346,1.060774
std,0.319881,0.905121,0.886427,0.544108,0.170229,0.313117,0.220224
min,0.500000,0.588235,0.500000,0.500000,0.500000,0.500000,0.500000
25%,0.740741,0.950243,0.666667,0.828571,0.666667,0.666667,0.960305
50%,0.857143,1.014925,0.756757,0.934461,0.751678,0.751678,1.003139
75%,0.957447,1.166667,0.875000,1.053292,0.875000,0.875000,1.084337
max,3.928571,8.000000,12.714286,5.153846,2.175000,4.396226,2.535211

In [136]:
normalized_df=(x - x.min()) / (x.max() - x.min())

normalized_df.head()

problemId,C,C++,Go,Java,Javascript,Python,Python3
5b5c8cd7276e2200208fed62,0.113084,0.062896,0.018709,0.106951,0.136431,0.058652,0.331156
5b645f711b2cd40020b6c771,0.097432,0.091584,0.014505,0.072974,0.105770,0.410028,0.272099
5b649819c0b1b80020eb30e1,0.228293,0.054779,0.027504,0.076853,0.200560,0.086221,0.287669
5b64600d1b2cd40020b6c772,0.154672,0.059644,0.000611,0.076124,0.004455,0.001915,0.260564
5b6c3ec18cab100020e963b7,0.111443,0.072951,0.019287,0.114502,0.140643,0.060463,0.387390

In [137]:
normalized_df.describe()

problemId,C,C++,Go,Java,Javascript,Python,Python3
count,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000
mean,0.112604,0.086999,0.029819,0.120509,0.167533,0.077600,0.275536
std,0.093299,0.122119,0.072573,0.116916,0.101629,0.080364,0.108207
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.070216,0.048842,0.013645,0.070602,0.099502,0.042776,0.226171
50%,0.104167,0.057569,0.021021,0.093355,0.150255,0.064595,0.247217
75%,0.133422,0.078042,0.030702,0.118889,0.223881,0.096247,0.287114
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [138]:
normalized_df.to_csv("../data/processed/success_score.csv")